/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal2023;

import ConexionDB.ConexionDB;
import Control_Usuarios.FormulariosCRUD;
import Control_Usuarios.PermisosCRUD;
import Control_Usuarios.UsuariosCRUD;
import Reportes.BotonesReportes;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell Vostro 7390
 */
public class menuprincipal extends javax.swing.JFrame {

    Connection con = null;
    ConexionDB conecta;
    String usuario, sentenciaSQL;
    PreparedStatement ps = null;
    ImageIcon icono;
    ResultSet rs = null;

    public menuprincipal() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public void conectarBD() {
        conecta = new ConexionDB("clinica_mateo");
        con = conecta.getConexion();
    }

    public boolean Acceso(String nombreUsuario, String nombreFormulario) {
        try {

            // Si el usuario es "admin", permitir el acceso completo al formulario
            if (UserAdmin(nombreUsuario) == true) {
                return true;
            }
            conectarBD();
            sentenciaSQL = "SELECT COUNT(*) FROM usuarios u JOIN permisos p ON u.nombre_usuario = p.usuario JOIN formularios f ON p.formulario = f.nombre_formulario WHERE u.nombre_usuario = ? AND f.nombre_formulario = ?";
            ps = con.prepareStatement(sentenciaSQL);
            ps.setString(1, nombreUsuario);
            ps.setString(2, nombreFormulario);

            rs = ps.executeQuery();
            rs.next();
            int numFilas = rs.getInt(1);
            con.close();
            return numFilas > 0;

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pueden validar los permisos del usuario! " + ex);
            return false;
        }
    }

    public boolean UserAdmin(String nombreUsuario) {
        try {
            conectarBD();
            sentenciaSQL = "SELECT COUNT(*) FROM usuarios WHERE nombre_usuario = ? and admin=1";
            ps = con.prepareStatement(sentenciaSQL);
            ps.setString(1, nombreUsuario);
            rs = ps.executeQuery();
            rs.next();
            int numFilas = rs.getInt(1);

            // Si el usuario es "administrado", permitir el acceso completo al formulario
            con.close();
            return numFilas > 0;

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pueden validar los permisos del usuario! " + ex);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContenedorPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        menuPacientes = new javax.swing.JMenu();
        menuEspecialidad = new javax.swing.JMenu();
        menuAdministrar = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuAcercaDe1 = new javax.swing.JMenu();
        menuAcercaDe2 = new javax.swing.JMenu();
        menuAcercaDe3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpContenedorPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondomenuprincipal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, 1430, -1));

        jdpContenedorPrincipal.add(jPanel1);
        jPanel1.setBounds(0, 0, 1410, 740);

        menuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/doctor.png"))); // NOI18N
        menuRegistrar.setMnemonic('e');
        menuRegistrar.setText("Doctores");
        menuRegistrar.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrarMouseClicked(evt);
            }
        });
        menuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarActionPerformed(evt);
            }
        });
        menuBar.add(menuRegistrar);

        menuPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paciente.png"))); // NOI18N
        menuPacientes.setText("Pacientes");
        menuPacientes.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPacientesMouseClicked(evt);
            }
        });
        menuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacientesActionPerformed(evt);
            }
        });
        menuBar.add(menuPacientes);

        menuEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/especialidad.png"))); // NOI18N
        menuEspecialidad.setText("Especialidad");
        menuEspecialidad.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuEspecialidad.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuEspecialidadMenuSelected(evt);
            }
        });
        menuEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEspecialidadMouseClicked(evt);
            }
        });
        menuEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEspecialidadActionPerformed(evt);
            }
        });
        menuBar.add(menuEspecialidad);

        menuAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        menuAdministrar.setText("Factura");
        menuAdministrar.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuAdministrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdministrarMouseClicked(evt);
            }
        });
        menuBar.add(menuAdministrar);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturadetalle.png"))); // NOI18N
        jMenu1.setText("Cobros Facturas");
        jMenu1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jMenu1.setHideActionText(true);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menuBar.add(jMenu1);

        menuAcercaDe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/citas.png"))); // NOI18N
        menuAcercaDe1.setText("Citas");
        menuAcercaDe1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuAcercaDe1.setHideActionText(true);
        menuAcercaDe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcercaDe1MouseClicked(evt);
            }
        });
        menuBar.add(menuAcercaDe1);

        menuAcercaDe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tratamiento.png"))); // NOI18N
        menuAcercaDe2.setText("Tratamiento");
        menuAcercaDe2.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuAcercaDe2.setHideActionText(true);
        menuAcercaDe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcercaDe2MouseClicked(evt);
            }
        });
        menuBar.add(menuAcercaDe2);

        menuAcercaDe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Report.png"))); // NOI18N
        menuAcercaDe3.setText("Reportes");
        menuAcercaDe3.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        menuAcercaDe3.setHideActionText(true);
        menuAcercaDe3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcercaDe3MouseClicked(evt);
            }
        });
        menuBar.add(menuAcercaDe3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jMenu2.setText("Usuarios");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        menuBar.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/forms.png"))); // NOI18N
        jMenu3.setText("Formularios");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        menuBar.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N
        jMenu4.setText("Permisos");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRegistrarActionPerformed

    private void menuEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEspecialidadActionPerformed

    }//GEN-LAST:event_menuEspecialidadActionPerformed

    private void menuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacientesActionPerformed

    }//GEN-LAST:event_menuPacientesActionPerformed

    private void menuEspecialidadMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuEspecialidadMenuSelected

    }//GEN-LAST:event_menuEspecialidadMenuSelected

    private void menuEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEspecialidadMouseClicked
        if (Acceso(usuario, "Especialidad")) {
            EspecialidadCRUD jframe = new EspecialidadCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Especialidad! ");
        }
    }//GEN-LAST:event_menuEspecialidadMouseClicked

    private void menuPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPacientesMouseClicked
        if (Acceso(usuario, "Pacientes")) {
            PacientesCRUD jframe = new PacientesCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario  Pacientes! ");
        }
    }//GEN-LAST:event_menuPacientesMouseClicked

    private void menuRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrarMouseClicked
        if (Acceso(usuario, "Doctores")) {
            DoctoresCRUD jframe = new DoctoresCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Doctores! ");
        }
    }//GEN-LAST:event_menuRegistrarMouseClicked

    private void menuAcercaDe3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcercaDe3MouseClicked
        if (Acceso(usuario, "Reportes")) {
            BotonesReportes jframe = new BotonesReportes();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso a los Reportes! ");
        }
    }//GEN-LAST:event_menuAcercaDe3MouseClicked

    private void menuAdministrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdministrarMouseClicked

        if (Acceso(usuario, "Factura")) {
            FacturaCRUD jframe = new FacturaCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Facturas! ");
        }
    }//GEN-LAST:event_menuAdministrarMouseClicked

    private void menuAcercaDe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcercaDe2MouseClicked

        if (Acceso(usuario, "Tratamiento")) {
            TratamientoCRUD jframe = new TratamientoCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Tratamiento! ");
        }
    }//GEN-LAST:event_menuAcercaDe2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        if (Acceso(usuario, "Cobros")) {
            CobrosFacturas jframe = new CobrosFacturas();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Cobros Facturas! ");
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void menuAcercaDe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcercaDe1MouseClicked
        if (Acceso(usuario, "Citas")) {
            CitasCRUD jframe = new CitasCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario citas! ");
        }

    }//GEN-LAST:event_menuAcercaDe1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        if (Acceso(usuario, "Usuarios")) {
            UsuariosCRUD jframe = new UsuariosCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Usuarios! ");
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        if (Acceso(usuario, "Formularios")) {
            FormulariosCRUD jframe = new FormulariosCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Formularios! ");
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        if (Acceso(usuario, "Permisos")) {
            PermisosCRUD jframe = new PermisosCRUD();
            jdpContenedorPrincipal.add(jframe);
            jframe.show();
        } else {
            // El usuario no tiene acceso al formulario
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso al formulario Permisos! ");
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JDesktopPane jdpContenedorPrincipal;
    public static javax.swing.JMenu menuAcercaDe1;
    public static javax.swing.JMenu menuAcercaDe2;
    public static javax.swing.JMenu menuAcercaDe3;
    public static javax.swing.JMenu menuAdministrar;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menuEspecialidad;
    public static javax.swing.JMenu menuPacientes;
    public static javax.swing.JMenu menuRegistrar;
    // End of variables declaration//GEN-END:variables
}
